### ISSUE TITLE
'Traditional' block IDs

### ISSUE THREAD

**Issue by DMHYT** [KanzakiMiner-Offical/Ender-IO-BE#1]
### I am currently on my way to finish making Avaritia mod for InnerCore, and as you may know, to craft infinity catalyst you will need all types of singularities (items made out of thousands of resource blocks). Talking about exactly EnderIO, from this mod there are used such items as: Nickel Singularity, Fluxed Singularity, Enderium Block, Steel Block and Dark Steel Block. As I can see by the current source code, you don't have nickel, electrum flux, enderium and steel resource blocks, but that's not the main question to you, you can add them later, and the compat will work even without them normally.
***
### And I would like you to make them like this: `blockDarkSteel`.
***
### So, please, change the function for IDs to change from `someResourceBlock` to `blockSomeResource`, and also add missing blocks in the near future. Thank you, waiting for your reply and actions)))

**Comment by KanzakiMiner-Offical** [comment]
hi, i don't remember Ender IO has Nickel, Electrum flux, Enderium and Steel. As for changing block id and function name, i will change it as soon as possible

**Comment by DMHYT** [comment]
Sorry, my bad, when I added the full recipe of the infinity catalyst, I googled each ingredient, and it was said that the following blocks are added by EnderIO. Maybe I missed something that time, sorry

**Comment by KanzakiMiner-Offical** [comment]
hmmm, maybe I'll do Thermal after finishing part of EnderIO.So you don't need to delete it.
And Are you the author of the VSDum Projects group?

**Comment by DMHYT** [comment]
Yes, it's me

**Comment by KanzakiMiner-Offical** [comment]
Can you help me in making bows?

**Comment by DMHYT** [comment]
Now my Infinity Bow is almost finished, but I got stuck at rotating and speeding up the arrow to the needed direction. When I complete it, as soon as I have free time, I'll make a native library to register custom bows.

**Comment by KanzakiMiner-Offical** [comment]
hmmm do you still need to change anything with EnderIO? I will do it too :D

**Comment by DMHYT** [comment]
Hmm, at the moment I see no problems, keep up the development, wish you good luck)
But only one thing: Forget! About! Freaking! MediaFire! Why the hell do you upload the mod there, if we already have a very convenient website (icmods.mineprogramming.org), which is integrated with Horizon itself so that you can download mods from there directly from the app?

**Comment by KanzakiMiner-Offical** [comment]
I don't want to upload the incomplete test version to this web.Of course, the 10a7b version will be uploaded to the web :D
